package com.limynl.project.entity.healthy;

import java.io.Serializable;
import java.util.Date;

public class CheckInfo implements Serializable {
    private String time;

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.vision1
     *
     * @mbggenerated
     */
    private String vision1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.vision2
     *
     * @mbggenerated
     */
    private String vision2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.pressure1
     *
     * @mbggenerated
     */
    private String pressure1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.pressure2
     *
     * @mbggenerated
     */
    private String pressure2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.heartbeat
     *
     * @mbggenerated
     */
    private String heartbeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.blindness
     *
     * @mbggenerated
     */
    private String blindness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.liver_function
     *
     * @mbggenerated
     */
    private String liverFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.vital_capacity
     *
     * @mbggenerated
     */
    private String vitalCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.oral_cavity
     *
     * @mbggenerated
     */
    private String oralCavity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.conclusion
     *
     * @mbggenerated
     */
    private String conclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.body_percentage
     *
     * @mbggenerated
     */
    private String bodyPercentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.body_fat
     *
     * @mbggenerated
     */
    private String bodyFat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_chack_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hm_chack_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.id
     *
     * @return the value of hm_chack_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.id
     *
     * @param id the value for hm_chack_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.user_id
     *
     * @return the value of hm_chack_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.user_id
     *
     * @param userId the value for hm_chack_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.height
     *
     * @return the value of hm_chack_info.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.height
     *
     * @param height the value for hm_chack_info.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.weight
     *
     * @return the value of hm_chack_info.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.weight
     *
     * @param weight the value for hm_chack_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.vision1
     *
     * @return the value of hm_chack_info.vision1
     *
     * @mbggenerated
     */
    public String getVision1() {
        return vision1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.vision1
     *
     * @param vision1 the value for hm_chack_info.vision1
     *
     * @mbggenerated
     */
    public void setVision1(String vision1) {
        this.vision1 = vision1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.vision2
     *
     * @return the value of hm_chack_info.vision2
     *
     * @mbggenerated
     */
    public String getVision2() {
        return vision2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.vision2
     *
     * @param vision2 the value for hm_chack_info.vision2
     *
     * @mbggenerated
     */
    public void setVision2(String vision2) {
        this.vision2 = vision2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.pressure1
     *
     * @return the value of hm_chack_info.pressure1
     *
     * @mbggenerated
     */
    public String getPressure1() {
        return pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.pressure1
     *
     * @param pressure1 the value for hm_chack_info.pressure1
     *
     * @mbggenerated
     */
    public void setPressure1(String pressure1) {
        this.pressure1 = pressure1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.pressure2
     *
     * @return the value of hm_chack_info.pressure2
     *
     * @mbggenerated
     */
    public String getPressure2() {
        return pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.pressure2
     *
     * @param pressure2 the value for hm_chack_info.pressure2
     *
     * @mbggenerated
     */
    public void setPressure2(String pressure2) {
        this.pressure2 = pressure2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.heartbeat
     *
     * @return the value of hm_chack_info.heartbeat
     *
     * @mbggenerated
     */
    public String getHeartbeat() {
        return heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.heartbeat
     *
     * @param heartbeat the value for hm_chack_info.heartbeat
     *
     * @mbggenerated
     */
    public void setHeartbeat(String heartbeat) {
        this.heartbeat = heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.blindness
     *
     * @return the value of hm_chack_info.blindness
     *
     * @mbggenerated
     */
    public String getBlindness() {
        return blindness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.blindness
     *
     * @param blindness the value for hm_chack_info.blindness
     *
     * @mbggenerated
     */
    public void setBlindness(String blindness) {
        this.blindness = blindness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.liver_function
     *
     * @return the value of hm_chack_info.liver_function
     *
     * @mbggenerated
     */
    public String getLiverFunction() {
        return liverFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.liver_function
     *
     * @param liverFunction the value for hm_chack_info.liver_function
     *
     * @mbggenerated
     */
    public void setLiverFunction(String liverFunction) {
        this.liverFunction = liverFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.vital_capacity
     *
     * @return the value of hm_chack_info.vital_capacity
     *
     * @mbggenerated
     */
    public String getVitalCapacity() {
        return vitalCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.vital_capacity
     *
     * @param vitalCapacity the value for hm_chack_info.vital_capacity
     *
     * @mbggenerated
     */
    public void setVitalCapacity(String vitalCapacity) {
        this.vitalCapacity = vitalCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.oral_cavity
     *
     * @return the value of hm_chack_info.oral_cavity
     *
     * @mbggenerated
     */
    public String getOralCavity() {
        return oralCavity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.oral_cavity
     *
     * @param oralCavity the value for hm_chack_info.oral_cavity
     *
     * @mbggenerated
     */
    public void setOralCavity(String oralCavity) {
        this.oralCavity = oralCavity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.remarks
     *
     * @return the value of hm_chack_info.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.remarks
     *
     * @param remarks the value for hm_chack_info.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.conclusion
     *
     * @return the value of hm_chack_info.conclusion
     *
     * @mbggenerated
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.conclusion
     *
     * @param conclusion the value for hm_chack_info.conclusion
     *
     * @mbggenerated
     */
    public void setConclusion(String conclusion) {
        this.conclusion = conclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.body_percentage
     *
     * @return the value of hm_chack_info.body_percentage
     *
     * @mbggenerated
     */
    public String getBodyPercentage() {
        return bodyPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.body_percentage
     *
     * @param bodyPercentage the value for hm_chack_info.body_percentage
     *
     * @mbggenerated
     */
    public void setBodyPercentage(String bodyPercentage) {
        this.bodyPercentage = bodyPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.body_fat
     *
     * @return the value of hm_chack_info.body_fat
     *
     * @mbggenerated
     */
    public String getBodyFat() {
        return bodyFat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.body_fat
     *
     * @param bodyFat the value for hm_chack_info.body_fat
     *
     * @mbggenerated
     */
    public void setBodyFat(String bodyFat) {
        this.bodyFat = bodyFat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.create_time
     *
     * @return the value of hm_chack_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.create_time
     *
     * @param createTime the value for hm_chack_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_chack_info.update_time
     *
     * @return the value of hm_chack_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_chack_info.update_time
     *
     * @param updateTime the value for hm_chack_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}