package com.limynl.project.entity.healthy;

import java.io.Serializable;
import java.util.Date;

public class JwsInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.brif
     *
     * @mbggenerated
     */
    private String brif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_jws_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hm_jws_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.id
     *
     * @return the value of hm_jws_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.id
     *
     * @param id the value for hm_jws_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.user_id
     *
     * @return the value of hm_jws_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.user_id
     *
     * @param userId the value for hm_jws_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.time
     *
     * @return the value of hm_jws_info.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.time
     *
     * @param time the value for hm_jws_info.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.content
     *
     * @return the value of hm_jws_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.content
     *
     * @param content the value for hm_jws_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.brif
     *
     * @return the value of hm_jws_info.brif
     *
     * @mbggenerated
     */
    public String getBrif() {
        return brif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.brif
     *
     * @param brif the value for hm_jws_info.brif
     *
     * @mbggenerated
     */
    public void setBrif(String brif) {
        this.brif = brif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.create_time
     *
     * @return the value of hm_jws_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.create_time
     *
     * @param createTime the value for hm_jws_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_jws_info.update_time
     *
     * @return the value of hm_jws_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_jws_info.update_time
     *
     * @param updateTime the value for hm_jws_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}